export const STORAGE_KEYS = {
  PROJECTS: 'projects',
  QUEUE_ORDER: 'queueOrder',
  GLOBAL_SETTINGS: 'globalSettings',
} as const;

export const MESSAGE_TYPES = {
  // Panel -> Background
  START_QUEUE: 'START_QUEUE',
  PAUSE_QUEUE: 'PAUSE_QUEUE',
  RESUME_QUEUE: 'RESUME_QUEUE',
  TERMINATE_QUEUE: 'TERMINATE_QUEUE',
  GET_PROJECTS: 'GET_PROJECTS',
  SAVE_PROJECT: 'SAVE_PROJECT',
  DELETE_PROJECT: 'DELETE_PROJECT',
  GET_TAB_STATUS: 'GET_TAB_STATUS',
  GET_GLOBAL_SETTINGS: 'GET_GLOBAL_SETTINGS',
  SAVE_GLOBAL_SETTINGS: 'SAVE_GLOBAL_SETTINGS',
  SET_QUEUE_ORDER: 'SET_QUEUE_ORDER',
  CLEAR_ALL_DATA: 'CLEAR_ALL_DATA',
  // Background -> Panel
  PROJECTS_UPDATED: 'PROJECTS_UPDATED',
  PROJECT_STARTED: 'PROJECT_STARTED',
  PROJECT_PROGRESS: 'PROJECT_PROGRESS',
  PROJECT_DONE: 'PROJECT_DONE',
  QUEUE_DONE: 'QUEUE_DONE',
  QUEUE_PAUSED: 'QUEUE_PAUSED',
  TAB_STATUS: 'TAB_STATUS',
  GLOBAL_SETTINGS: 'GLOBAL_SETTINGS',
  ERROR: 'ERROR',
  // Background -> Content
  RUN_PROJECT: 'RUN_PROJECT',
  // Content -> Background
  DOWNLOAD_REQUEST: 'DOWNLOAD_REQUEST',
  CONTENT_READY: 'CONTENT_READY',
  DOWNLOAD_SAVE_AS_TIP: 'DOWNLOAD_SAVE_AS_TIP',
} as const;

export const GROK_ORIGIN = 'https://grok.com';
export const GROK_IMAGINE_URL = 'https://grok.com/imagine';

export const DOWNLOAD_FOLDER_PREFIX = 'GrokAutomation';
